---
- name: Create user
  ansible.builtin.user:
    state: present
    name: ansible
    shell: /bin/bash
    create_home: true
    password: password
    groups: sudo
    append: true
    comment: Usuario para correr playbook de ansible
...
