---
# Aquí se declararan las variables utilizadas an en los proxy padre e hijos 
# Variables comunes para ambos proxys
# En 
squid_visible: NOT-SHOW-FOR-NOW
squid_logformat: "%9d.%03d %6d %s %s/%03d %d %s %s %s %s%s/%s %s"

# Puertos usados en los proxys
# igual se puede usar el mismo para todos
squid_http_port_hijo: 3128
squid_http_port_padre1: 3129
squid_http_port_padre2: 3130
squid_http_port_padre3: 3131

# ---------------------------------------------------------------------------------
# Solo para proxy hijo

# Autenticaci'on kerberos
squid_kerberos_host: fqdn_del_servidor_proxy
squid_kerberos_realm: DOMINIO

# Cache_peer proxy hijo
squid_cache_peer_hostname1: proxy_padre1
squid_cache_peer_hostname2: proxy_padre2
squid_cache_peer_hostname3: proxy_padre3
squid_cache_peer_type: parent
squid_cache_peer_icpport: 0
squid_cache_peer_options: no-query default round-robin no-digest weighted-round-robin

# Defino camino para guardar los LOG
# En la configuración se ve mucho más claro, se define este camino por que se van a separar
# los log por ciudades, es decir será un solo proxy que brinde servicios a 14 ciudades o provincias
squid_log_path: "/media/LOG"

# Defino camino para mover los log a la nube
squid_cloud_path: "/media/FILES/NEXTCLOUD/data/log_proxy/files/SALVAS/PROXY"

# Defino ruta para cargar configuraciones extras
squid_include_path: "/etc/squid/conf.d"

# Definir bloques IP por provincias
# Esto es un diccionario
squid_provincias:
  cuidad_1:
    x.x.x.x/24
  ciudad_2:
    y.y.y.y/24
# ---------------------------------------------------------------------------------
# Solo para proxy padre, definos los permisos de accesos
# por supuesto que se pone solo el permiso de los proxy hijos
squid_acl_padre:
  - {name: 'proxy_hijo', type: 'src', arg: 'z.z.z.z/24'}
squid_http_access_padre:
  - {state: 'allow', acl: 'proxy_hijo'}
...
