---
all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3
    ansible_private_key_file: /home/ansible/.ssh/id_rsa

  children:
    with_proxy:
      hosts:
        mailad.encc.cupet.cu:
          ansible_host: 172.16.21.67
        mailbackup.encc.cupet.cu:
          ansible_host: 172.18.61.6
        encc132.encc.cupet.cu:
          ansible_host: 172.16.21.132
        samba4.encc.cupet.cu:
          ansible_host: 172.16.21.4
        nextcloud.encc.cupet.cu:
          ansible_host: 172.16.21.5
        dns.encc.cupet.cu:
          ansible_host: 172.16.21.68
        openkm.encc.cupet.cu:
          ansible_host: 172.16.21.70
        dns_backup.encc.cupet.cu:
          ansible_host: 172.18.61.3

    without_proxy:
      hosts:
        proxy69.encc.cupet.cu:
          ansible_host: 172.16.21.69
        proxy130.encc.cupet.cu:
          ansible_host: 172.16.21.130
        proxy196.encc.cupet.cu:
          ansible_host: 172.16.21.196
        proxy197.encc.cupet.cu:
          ansible_host: 172.16.21.197
...
