---
all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3
    ansible_private_key_file: /home/ansible/.ssh/id_rsa

  children:
    # Necesitan proxy
    with_proxy:
      hosts:
        servidor_1:
          ansible_host: ip_servidor_1
        servidor_2:
          ansible_host: ip_servidor_2
    
    # No necesitan proxy      
    without_proxy:
      hosts:
        servidor_3:
          ansible_host: ip_servidor_3
        servidor_4:
          ansible_host: ip_servidor_4
        proxy196.encc.cupet.cu:
...
