---
# Crear el directorio de los log
# El contenido del directorio LOG ser'an las provincias
# ansible.builtin.file gestiona archivos, directorios y enlaces simbólicos
# ansible.builtin.stat obtiene información de archivo/directorio sin modificarlo

- name: Separamos log de las provincias
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: proxy
    group: proxy
    mode: '0755'
  loop:
    - "{{ squid_log_path }}/ciudad_1"
    - "{{ squid_log_path }}/ciudad_2"
    
- name: Crear si no existe fichero por provincias(LOG)
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    owner: proxy
    group: proxy
    mode: '0755'
  loop:
    - "{{ squid_log_path }}/ciudad_1/ciudad_1.log"
    - "{{ squid_log_path }}/ciudad_1/ciudad_2.log"
  when: not item is exists
...
