---
# Crear el directorio de los log
# El contenido del directorio LOG ser'an las provincias
# ansible.builtin.file gestiona archivos, directorios y enlaces simbólicos
# ansible.builtin.stat obtiene información de archivo/directorio sin modificarlo

- name: Creamos la carpeta si no existe
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ squid_cloud_path }}/ciudad_1"
    - "{{ squid_cloud_path }}/ciudad_2"
    
- name: Copiamos los log para la nube
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0755'
  loop:
    - {src: '{{ squid_log_path }}/ciudad_1/', dest: '{{ squid_cloud_path }}/ciudad_1/'}
    - {src: '{{ squid_log_path }}/ciudad_2/', dest: '{{ squid_cloud_path }}/ciudad_2/'}
...
