---
# Crear el directorio de los log
# El contenido del directorio LOG ser'an las provincias
# ansible.builtin.file gestiona archivos, directorios y enlaces simbólicos
# ansible.builtin.stat obtiene información de archivo/directorio sin modificarlo

- name: Separamos log de las provincias
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: proxy
    group: proxy
    mode: '0755'
  loop:
    - "{{ squid_log_path }}/gtm"
    - "{{ squid_log_path }}/stg"
    - "{{ squid_log_path }}/hlg"
    - "{{ squid_log_path }}/grm"
    - "{{ squid_log_path }}/ltu"
    - "{{ squid_log_path }}/cmg"
    - "{{ squid_log_path }}/cav"
    - "{{ squid_log_path }}/ssp"
    - "{{ squid_log_path }}/vcl"
    - "{{ squid_log_path }}/cfg"
    - "{{ squid_log_path }}/mtz"
    - "{{ squid_log_path }}/enc"
    - "{{ squid_log_path }}/pri"
    - "{{ squid_log_path }}/isj"

# Ya creados los directorios, se crean los ficheros log
# Seg'un la literatura es mejor usar loop que with_items
# este ultimo es la versio'n vieja

- name: Crear si no existe fichero por provincias(LOG)
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    owner: proxy
    group: proxy
    mode: '0755'
  loop:
    - "{{ squid_log_path }}/gtm/gtm.log"
    - "{{ squid_log_path }}/stg/stg.log"
    - "{{ squid_log_path }}/hlg/hlg.log"
    - "{{ squid_log_path }}/grm/grm.log"
    - "{{ squid_log_path }}/ltu/ltu.log"
    - "{{ squid_log_path }}/cmg/cmg.log"
    - "{{ squid_log_path }}/cav/cav.log"
    - "{{ squid_log_path }}/ssp/ssp.log"
    - "{{ squid_log_path }}/vcl/vcl.log"
    - "{{ squid_log_path }}/cfg/cfg.log"
    - "{{ squid_log_path }}/mtz/mtz.log"
    - "{{ squid_log_path }}/enc/enc.log"
    - "{{ squid_log_path }}/pri/pri.log"
    - "{{ squid_log_path }}/isj/isj.log"
  when: not item is exists
...
